//All countries

const all_countries = {
  "GY": { "es": "Guyana", "en": "Guyana", "coordinates": { "lat": 4.8604, "lng": -58.9302 } },
  "DM": { "es": "Dominica", "en": "Dominica", "coordinates": { "lat": 15.4148, "lng": -61.3707 } },
  "AG": {"es": "Antigua y Barbuda","en": "Antigua and Barbuda","coordinates": {"lat": 17.0608,"lng": -61.7964}},
  "MS": { "es": "Montserrat", "en": "Montserrat", "coordinates": { "lat": 16.7425, "lng": -62.2181 } },
"GS": {"es": "Islas Georgias del Sur y Sandwich del Sur","en": "South Georgia and South Sandwich Islands","coordinates": {"lat": -54.4296,"lng": -36.5870}},

  "VI": { "es": "Islas Vírgenes", "en": "United States Virgin Islands", "coordinates": { "lat": 18.3358, "lng": -64.8963 } },
  "FK": { "es": "Islas Malvinas", "en": "Falkland Islands", "coordinates": { "lat": -51.6966, "lng": -57.8600 } },
  "AF": { "es": "Afganistán", "en": "Afghanistan", "coordinates": { "lat": 34.5553, "lng": 69.2075 } },
  "AX": { "es": "Islas Åland", "en": "Åland Islands", "coordinates": { "lat": 60.1226, "lng": 19.9344 } },
  "AL": { "es": "Albania", "en": "Albania", "coordinates": { "lat": 41.3275, "lng": 19.8189 } },
  "DZ": { "es": "Argelia", "en": "Algeria", "coordinates": { "lat": 36.737232, "lng": 3.086472 } },
  "AS": { "es": "Samoa Americana", "en": "American Samoa", "coordinates": { "lat": -14.2700, "lng": -170.1323 } },
  "AD": { "es": "Andorra", "en": "Andorra", "coordinates": { "lat": 42.5078, "lng": 1.5211 } },
  "AO": { "es": "Angola", "en": "Angola", "coordinates": { "lat": -8.8390, "lng": 13.2894 } },
  "AI": { "es": "Anguila", "en": "Anguilla", "coordinates": { "lat": 18.2206, "lng": -63.0686 } },
  "AQ": { "es": "Antártida", "en": "Antarctica", "coordinates": { "lat": -82.8628, "lng": 135.0000 } },
  "AR": { "es": "Argentina", "en": "Argentina", "coordinates": { "lat": -34.6037, "lng": -58.3816 } },
  "AM": { "es": "Armenia", "en": "Armenia", "coordinates": { "lat": 40.1792, "lng": 44.4991 } },
  "AW": { "es": "Aruba", "en": "Aruba", "coordinates": { "lat": 12.5211, "lng": -69.9683 } },
  "AU": { "es": "Australia", "en": "Australia", "coordinates": { "lat": -35.2809, "lng": 149.1300 } },
  "AT": { "es": "Austria", "en": "Austria", "coordinates": { "lat": 48.2082, "lng": 16.3738 } },
  "AZ": { "es": "Azerbaiyán", "en": "Azerbaijan", "coordinates": { "lat": 40.4093, "lng": 49.8671 } },
  "BS": { "es": "Bahamas", "en": "The Bahamas", "coordinates": { "lat": 25.0343, "lng": -77.3963 } },
  "BH": { "es": "Baréin", "en": "Bahrain", "coordinates": { "lat": 26.0667, "lng": 50.5577 } },
  "BD": { "es": "Bangladés", "en": "Bangladesh", "coordinates": { "lat": 23.8103, "lng": 90.4125 } },
  "BB": { "es": "Barbados", "en": "Barbados", "coordinates": { "lat": 13.1939, "lng": -59.5432 } },
  "BY": { "es": "Bielorrusia", "en": "Belarus", "coordinates": { "lat": 53.9, "lng": 27.5667 } },
  "BE": { "es": "Bélgica", "en": "Belgium", "coordinates": { "lat": 50.8503, "lng": 4.3517 } },
  "BZ": { "es": "Belice", "en": "Belize", "coordinates": { "lat": 17.1899, "lng": -88.4976 } },
  "BJ": { "es": "Benín", "en": "Benin", "coordinates": { "lat": 6.3603, "lng": 2.4279 } },
  "BM": { "es": "Bermudas", "en": "Bermuda", "coordinates": { "lat": 32.3078, "lng": -64.7505 } },
  "BT": { "es": "Bután", "en": "Bhutan", "coordinates": { "lat": 27.4710, "lng": 89.6395 } },
  "BO": { "es": "Bolivia", "en": "Bolivia", "coordinates": { "lat": -16.5000, "lng": -68.1193 } },
  "BA": { "es": "Bosnia y Herzegovina", "en": "Bosnia and Herzegovina", "coordinates": { "lat": 43.8486, "lng": 18.3564 } },
  "BW": { "es": "Botsuana", "en": "Botswana", "coordinates": { "lat": -24.6587, "lng": 25.9086 } },
  "BR": { "es": "Brasil", "en": "Brazil", "coordinates": { "lat": -15.7801, "lng": -47.9292 } },
  "IO": { "es": "Territorio Británico del Océano Índico", "en": "British Indian Ocean Territory", "coordinates": { "lat": -6.3432, "lng": 71.8767 } },
  "BN": { "es": "Brunéi", "en": "Brunei", "coordinates": { "lat": 4.9031, "lng": 114.9398 } },
  "BG": { "es": "Bulgaria", "en": "Bulgaria", "coordinates": { "lat": 42.6977, "lng": 23.3219 } },
  "BF": { "es": "Burkina Faso", "en": "Burkina Faso", "coordinates": { "lat": 12.6392, "lng": -8.0029 } },
  "BI": { "es": "Burundi", "en": "Burundi", "coordinates": { "lat": -3.3731, "lng": 29.9187 } },
  "KH": { "es": "Camboya", "en": "Cambodia", "coordinates": { "lat": 11.5564, "lng": 104.9282 } },
  "CM": { "es": "Camerún", "en": "Cameroon", "coordinates": { "lat": 3.8480, "lng": 11.5021 } },
  "CA": { "es": "Canadá", "en": "Canada", "coordinates": { "lat": 45.4215, "lng": -75.6972 } },
  "CV": { "es": "Cabo Verde", "en": "Cape Verde", "coordinates": { "lat": 14.9330, "lng": -23.5120 } },
  "KY": { "es": "Islas Caimán", "en": "Cayman Islands", "coordinates": { "lat": 19.3131, "lng": -81.2546 } },
  "CF": { "es": "República Centroafricana", "en": "Central African Republic", "coordinates": { "lat": 4.3947, "lng": 18.5582 } },
  "TD": { "es": "Chad", "en": "Chad", "coordinates": { "lat": 12.6348, "lng": 14.8485 } },
  "CL": { "es": "Chile", "en": "Chile", "coordinates": { "lat": -33.4489, "lng": -70.6693 } },
  "CN": { "es": "China", "en": "China", "coordinates": { "lat": 39.9042, "lng": 116.4074 } },
  "CX": { "es": "Isla Christmas", "en": "Christmas Island", "coordinates": { "lat": -10.4475, "lng": 105.6904 } },
  "CC": { "es": "Islas Cocos", "en": "Cocos (Keeling) Islands", "coordinates": { "lat": -12.1642, "lng": 96.8709 } },
  "CO": { "es": "Colombia", "en": "Colombia", "coordinates": { "lat": 4.7110, "lng": -74.0721 } },
  "KM": { "es": "Comoras", "en": "Comoros", "coordinates": { "lat": -11.7011, "lng": 43.2547 } },
  "CG": { "es": "República del Congo", "en": "Congo", "coordinates": { "lat": -4.2634, "lng": 15.2429 } },
  "CD": { "es": "República Democrática del Congo", "en": "Democratic Republic of the Congo", "coordinates": { "lat": -4.4419, "lng": 15.2663 } },
  "CK": { "es": "Islas Cook", "en": "Cook Islands", "coordinates": { "lat": -21.2367, "lng": -159.7777 } },
  "CR": { "es": "Costa Rica", "en": "Costa Rica", "coordinates": { "lat": 9.9333, "lng": -84.0833 } },
  "HR": { "es": "Croacia", "en": "Croatia", "coordinates": { "lat": 45.1, "lng": 15.2 } },
  "CU": { "es": "Cuba", "en": "Cuba", "coordinates": { "lat": 23.1136, "lng": -82.3666 } },
  "CY": { "es": "Chipre", "en": "Cyprus", "coordinates": { "lat": 35.1264, "lng": 33.4299 } },
  "CZ": { "es": "República Checa", "en": "Czech Republic", "coordinates": { "lat": 50.0755, "lng": 14.4378 } },
  "DK": { "es": "Dinamarca", "en": "Denmark", "coordinates": { "lat": 55.6761, "lng": 12.5683 } },
  "DJ": { "es": "Yibuti", "en": "Djibouti", "coordinates": { "lat": 11.8251, "lng": 42.5903 } },
  "DO": { "es": "República Dominicana", "en": "Dominican Republic", "coordinates": { "lat": 18.7357, "lng": -70.1627 } },
  "EC": { "es": "Ecuador", "en": "Ecuador", "coordinates": { "lat": -0.1807, "lng": -78.4678 } },
  "EG": { "es": "Egipto", "en": "Egypt", "coordinates": { "lat": 30.0444, "lng": 31.2357 } },
  "SV": { "es": "El Salvador", "en": "El Salvador", "coordinates": { "lat": 13.6929, "lng": -89.2182 } },
  "GQ": { "es": "Guinea Ecuatorial", "en": "Equatorial Guinea", "coordinates": { "lat": 3.7500, "lng": 8.7833 } },
  "ER": { "es": "Eritrea", "en": "Eritrea", "coordinates": { "lat": 15.3229, "lng": 38.9251 } },
  "EE": { "es": "Estonia", "en": "Estonia", "coordinates": { "lat": 59.4370, "lng": 24.7535 } },
  "SZ": { "es": "Esuatini", "en": "Eswatini", "coordinates": { "lat": -26.5225, "lng": 31.4659 } },
  "ET": { "es": "Etiopía", "en": "Ethiopia", "coordinates": { "lat": 9.145, "lng": 40.4897 } },
  "FJ": { "es": "Fiyi", "en": "Fiji", "coordinates": { "lat": -17.7134, "lng": 178.0650 } },
  "FI": { "es": "Finlandia", "en": "Finland", "coordinates": { "lat": 60.1699, "lng": 24.9384 } },
  "FR": { "es": "Francia", "en": "France", "coordinates": { "lat": 48.8566, "lng": 2.3522 } },
  "PF": { "es": "Polinesia Francesa", "en": "French Polynesia", "coordinates": { "lat": -17.6509, "lng": -149.4260 } },
  "GA": { "es": "Gabón", "en": "Gabon", "coordinates": { "lat": 0.4167, "lng": 9.45 } },
  "GM": { "es": "Gambia", "en": "Gambia", "coordinates": { "lat": 13.4549, "lng": -16.5790 } },
  "GE": { "es": "Georgia", "en": "Georgia", "coordinates": { "lat": 41.7151, "lng": 44.8271 } },
  "DE": { "es": "Alemania", "en": "Germany", "coordinates": { "lat": 52.52, "lng": 13.4050 } },
  "GH": { "es": "Ghana", "en": "Ghana", "coordinates": { "lat": 5.5600, "lng": -0.2050 } },
  "GR": { "es": "Grecia", "en": "Greece", "coordinates": { "lat": 37.9838, "lng": 23.7275 } },
  "GL": { "es": "Groenlandia", "en": "Greenland", "coordinates": { "lat": 64.1814, "lng": -51.7216 } },
  "GD": { "es": "Granada", "en": "Grenada", "coordinates": { "lat": 12.1165, "lng": -61.6790 } },
  "GU": { "es": "Guam", "en": "Guam", "coordinates": { "lat": 13.4443, "lng": 144.7937 } },
  "GT": { "es": "Guatemala", "en": "Guatemala", "coordinates": { "lat": 14.6349, "lng": -90.5069 } },
  "GN": { "es": "Guinea", "en": "Guinea", "coordinates": { "lat": 9.5095, "lng": -13.7122 } },
  "GW": { "es": "Guinea-Bisáu", "en": "Guinea-Bissau", "coordinates": { "lat": 11.8192, "lng": -15.1804 } },
  "HT": { "es": "Haití", "en": "Haiti", "coordinates": { "lat": 18.5943, "lng": -72.3074 } },
  "HN": { "es": "Honduras", "en": "Honduras", "coordinates": { "lat": 13.9670, "lng": -85.9450 } },
  "HK": { "es": "Hong Kong", "en": "Hong Kong", "coordinates": { "lat": 22.3193, "lng": 114.1694 } },
  "HU": { "es": "Hungría", "en": "Hungary", "coordinates": { "lat": 47.4979, "lng": 19.0402 } },
  "IS": { "es": "Islandia", "en": "Iceland", "coordinates": { "lat": 64.1355, "lng": -21.8954 } },
  "IN": { "es": "India", "en": "India", "coordinates": { "lat": 28.6139, "lng": 77.2090 } },
  "ID": { "es": "Indonesia", "en": "Indonesia", "coordinates": { "lat": -6.2088, "lng": 106.8456 } },
  "IR": { "es": "Irán", "en": "Iran", "coordinates": { "lat": 35.6892, "lng": 51.3890 } },
  "IQ": { "es": "Irak", "en": "Iraq", "coordinates": { "lat": 33.3152, "lng": 44.3661 } },
  "IE": { "es": "Irlanda", "en": "Ireland", "coordinates": { "lat": 53.3498, "lng": -6.2603 } },
  "IL": { "es": "Israel", "en": "Israel", "coordinates": { "lat": 31.7683, "lng": 35.2137 } },
  "IT": { "es": "Italia", "en": "Italy", "coordinates": { "lat": 41.9028, "lng": 12.4964 } },
  "JM": { "es": "Jamaica", "en": "Jamaica", "coordinates": { "lat": 17.9714, "lng": -76.7921 } },
  "JP": { "es": "Japón", "en": "Japan", "coordinates": { "lat": 35.6762, "lng": 139.6503 } },
  "JO": { "es": "Jordania", "en": "Jordan", "coordinates": { "lat": 31.9554, "lng": 35.9450 } },
  "KZ": { "es": "Kazajistán", "en": "Kazakhstan", "coordinates": { "lat": 51.1694, "lng": 71.4491 } },
  "KE": { "es": "Kenia", "en": "Kenya", "coordinates": { "lat": -1.2921, "lng": 36.8219 } },
  "KI": { "es": "Kiribati", "en": "Kiribati", "coordinates": { "lat": -1.4516, "lng": 173.0310 } },
  "KW": { "es": "Kuwait", "en": "Kuwait", "coordinates": { "lat": 29.3759, "lng": 47.9774 } },
  "KG": { "es": "Kirguistán", "en": "Kyrgyzstan", "coordinates": { "lat": 42.8746, "lng": 74.6122 } },
  "LA": { "es": "Laos", "en": "Laos", "coordinates": { "lat": 17.9757, "lng": 102.6331 } },
  "LV": { "es": "Letonia", "en": "Latvia", "coordinates": { "lat": 56.946, "lng": 24.1059 } },
  "LB": { "es": "Líbano", "en": "Lebanon", "coordinates": { "lat": 33.8886, "lng": 35.4955 } },
  "LS": { "es": "Lesoto", "en": "Lesotho", "coordinates": { "lat": -29.6091, "lng": 28.2336 } },
  "LR": { "es": "Liberia", "en": "Liberia", "coordinates": { "lat": 6.4281, "lng": -9.4295 } },
  "LY": { "es": "Libia", "en": "Libya", "coordinates": { "lat": 32.8797, "lng": 13.1913 } },
  "LI": { "es": "Liechtenstein", "en": "Liechtenstein", "coordinates": { "lat": 47.1415, "lng": 9.5215 } },
  "LT": { "es": "Lituania", "en": "Lithuania", "coordinates": { "lat": 54.6892, "lng": 25.2798 } },
  "LU": { "es": "Luxemburgo", "en": "Luxembourg", "coordinates": { "lat": 49.6117, "lng": 6.13 } },
  "MO": { "es": "Macao", "en": "Macao", "coordinates": { "lat": 22.1987, "lng": 113.5439 } },
  "MK": { "es": "Macedonia", "en": "Macedonia", "coordinates": { "lat": 41.9981, "lng": 21.4254 } },
  "MG": { "es": "Madagascar", "en": "Madagascar", "coordinates": { "lat": -18.8792, "lng": 47.5079 } },
  "MW": { "es": "Malaui", "en": "Malawi", "coordinates": { "lat": -13.2543, "lng": 34.3015 } },
  "MY": { "es": "Malasia", "en": "Malaysia", "coordinates": { "lat": 3.1390, "lng": 101.6869 } },
  "MV": { "es": "Maldivas", "en": "Maldives", "coordinates": { "lat": 4.1755, "lng": 73.5093 } },
  "ML": { "es": "Malí", "en": "Mali", "coordinates": { "lat": 12.6392, "lng": -8.0029 } },
  "MT": { "es": "Malta", "en": "Malta", "coordinates": { "lat": 35.8997, "lng": 14.5147 } },
  "MH": { "es": "Islas Marshall", "en": "Marshall Islands", "coordinates": { "lat": 7.0654, "lng": 171.0703 } },
  "MR": { "es": "Mauritania", "en": "Mauritania", "coordinates": { "lat": 18.0792, "lng": -15.9750 } },
  "MU": { "es": "Mauricio", "en": "Mauritius", "coordinates": { "lat": -20.3484, "lng": 57.5522 } },
  "YT": { "es": "Mayotte", "en": "Mayotte", "coordinates": { "lat": -12.8275, "lng": 45.1663 } },
  "MX": { "es": "México", "en": "Mexico", "coordinates": { "lat": 19.4326, "lng": -99.1332 } },
  "FM": { "es": "Micronesia", "en": "Federated States of Micronesia", "coordinates": { "lat": 6.915, "lng": 158.1699 } },
  "MD": { "es": "Moldavia", "en": "Moldova", "coordinates": { "lat": 47.0105, "lng": 28.8638 } },
  "MC": { "es": "Mónaco", "en": "Monaco", "coordinates": { "lat": 43.7333, "lng": 7.4167 } },
  "MN": { "es": "Mongolia", "en": "Mongolia", "coordinates": { "lat": 47.8864, "lng": 106.9057 } },
  "ME": { "es": "Montenegro", "en": "Montenegro", "coordinates": { "lat": 42.4411, "lng": 19.2636 } },
  "MA": { "es": "Marruecos", "en": "Morocco", "coordinates": { "lat": 34.0209, "lng": -6.8416 } },
  "MZ": { "es": "Mozambique", "en": "Mozambique", "coordinates": { "lat": -25.9653, "lng": 32.5890 } },
  "MM": { "es": "Myanmar", "en": "Myanmar", "coordinates": { "lat": 16.8409, "lng": 96.1735 } },
  "NA": { "es": "Namibia", "en": "Namibia", "coordinates": { "lat": -22.5597, "lng": 17.0836 } },
  "NR": { "es": "Nauru", "en": "Nauru", "coordinates": { "lat": -0.5228, "lng": 166.9315 } },
  "NP": { "es": "Nepal", "en": "Nepal", "coordinates": { "lat": 27.7172, "lng": 85.3240 } },
  "NL": { "es": "Países Bajos", "en": "Netherlands", "coordinates": { "lat": 52.3676, "lng": 4.9041 } },
  "NC": { "es": "Nueva Caledonia", "en": "New Caledonia", "coordinates": { "lat": -22.2763, "lng": 166.4572 } },
  "NZ": { "es": "Nueva Zelanda", "en": "New Zealand", "coordinates": { "lat": -41.2867, "lng": 174.7762 } },
  "NI": { "es": "Nicaragua", "en": "Nicaragua", "coordinates": { "lat": 12.1364, "lng": -86.2514 } },
  "NE": { "es": "Níger", "en": "Niger", "coordinates": { "lat": 13.5120, "lng": 2.1128 } },
  "NG": { "es": "Nigeria", "en": "Nigeria", "coordinates": { "lat": 9.0579, "lng": 7.4951 } },
  "NU": { "es": "Niue", "en": "Niue", "coordinates": { "lat": -19.033, "lng": -169.8671 } },
  "NF": { "es": "Isla Norfolk", "en": "Norfolk Island", "coordinates": { "lat": -29.0408, "lng": 167.9541 } },
  "KP": { "es": "Corea del Norte", "en": "North Korea", "coordinates": { "lat": 39.0392, "lng": 125.7625 } },
  "MP": { "es": "Islas Marianas del Norte", "en": "Northern Mariana Islands", "coordinates": { "lat": 14.8042, "lng": 145.7360 } },
  "NO": { "es": "Noruega", "en": "Norway", "coordinates": { "lat": 59.9139, "lng": 10.7461 } },
  "OM": { "es": "Omán", "en": "Oman", "coordinates": { "lat": 23.5859, "lng": 58.4059 } },
  "PK": { "es": "Pakistán", "en": "Pakistan", "coordinates": { "lat": 33.6844, "lng": 73.0479 } },
  "PW": { "es": "Palaos", "en": "Palau", "coordinates": { "lat": 7.5148, "lng": 134.5825 } },
  "PA": { "es": "Panamá", "en": "Panama", "coordinates": { "lat": 8.9824, "lng": -79.5190 } },
  "PG": { "es": "Papúa Nueva Guinea", "en": "Papua New Guinea", "coordinates": { "lat": -9.4438, "lng": 147.1803 } },
  "PY": { "es": "Paraguay", "en": "Paraguay", "coordinates": { "lat": -25.2637, "lng": -57.5759 } },
  "PE": { "es": "Perú", "en": "Peru", "coordinates": { "lat": -12.0464, "lng": -77.0428 } },
  "PH": { "es": "Filipinas", "en": "Philippines", "coordinates": { "lat": 14.5995, "lng": 120.9842 } },
  "PL": { "es": "Polonia", "en": "Poland", "coordinates": { "lat": 52.2298, "lng": 21.0118 } },
  "PT": { "es": "Portugal", "en": "Portugal", "coordinates": { "lat": 38.7169, "lng": -9.1395 } },
  "PR": { "es": "Puerto Rico", "en": "Puerto Rico", "coordinates": { "lat": 18.4655, "lng": -66.1057 } },
  "QA": { "es": "Catar", "en": "Qatar", "coordinates": { "lat": 25.276987, "lng": 51.520008 } },
  "RO": { "es": "Rumanía", "en": "Romania", "coordinates": { "lat": 44.4268, "lng": 26.1025 } },
  "RU": { "es": "Rusia", "en": "Russia", "coordinates": { "lat": 55.7558, "lng": 37.6176 } },
  "RW": { "es": "Ruanda", "en": "Rwanda", "coordinates": { "lat": -1.9403, "lng": 29.8739 } },
  "RE": { "es": "Reunión", "en": "Reunion", "coordinates": { "lat": -20.9584, "lng": 55.2913 } },
  "BL": { "es": "San Bartolomé", "en": "Saint Barthelemy", "coordinates": { "lat": 17.8946, "lng": -62.8497 } },
  "SH": { "es": "Santa Elena", "en": "Saint Helena", "coordinates": { "lat": -15.931, "lng": -5.0707 } },
  "KN": { "es": "San Cristóbal y Nieves", "en": "Saint Kitts and Nevis", "coordinates": { "lat": 17.3578, "lng": -62.7826 } },
  "LC": { "es": "Santa Lucía", "en": "Saint Lucia", "coordinates": { "lat": 13.9970, "lng": -61.0980 } },
  "MF": { "es": "San Martín", "en": "Saint Martin", "coordinates": { "lat": 18.0708, "lng": -63.0803 } },
  "PM": { "es": "San Pedro y Miquelón", "en": "Saint Pierre and Miquelon", "coordinates": { "lat": 46.8853, "lng": -56.3159 } },
  "VC": { "es": "San Vicente y las Granadinas", "en": "Saint Vincent and the Grenadines", "coordinates": { "lat": 13.1031, "lng": -61.2200 } },
  "WS": { "es": "Samoa", "en": "Samoa", "coordinates": { "lat": -13.7590, "lng": -172.1046 } },
  "ST": { "es": "Santo Tomé y Príncipe", "en": "Sao Tome and Principe", "coordinates": { "lat": 0.1864, "lng": 6.6131 } },
  "SA": { "es": "Arabia Saudita", "en": "Saudi Arabia", "coordinates": { "lat": 24.7136, "lng": 46.6753 } },
  "SN": { "es": "Senegal", "en": "Senegal", "coordinates": { "lat": 14.6928, "lng": -17.4467 } },
  "RS": { "es": "Serbia", "en": "Republic of Serbia", "coordinates": { "lat": 44.8176, "lng": 20.4633 } },
  "SC": { "es": "Seychelles", "en": "Seychelles", "coordinates": { "lat": -4.6701, "lng": 55.4976 } },
  "SL": { "es": "Sierra Leona", "en": "Sierra Leone", "coordinates": { "lat": 8.4650, "lng": -13.2325 } },
  "SG": { "es": "Singapur", "en": "Singapore", "coordinates": { "lat": 1.2891, "lng": 103.8501 } },
  "SX": { "es": "San Martín (Países Bajos)", "en": "Sint Maarten", "coordinates": { "lat": 18.0425, "lng": -63.0601 } },
  "SK": { "es": "Eslovaquia", "en": "Slovakia", "coordinates": { "lat": 48.1482, "lng": 17.1067 } },
  "SI": { "es": "Eslovenia", "en": "Slovenia", "coordinates": { "lat": 46.0511, "lng": 14.5051 } },
  "SO": { "es": "Somalia", "en": "Somalia", "coordinates": { "lat": 2.0469, "lng": 45.3182 } },
  "ZA": { "es": "Sudáfrica", "en": "South Africa", "coordinates": { "lat": -25.7461, "lng": 28.1881 } },
  "ES": { "es": "España", "en": "Spain", "coordinates": { "lat": 40.4168, "lng": -3.7038 } },
  "LK": { "es": "Sri Lanka", "en": "Sri Lanka", "coordinates": { "lat": 6.9271, "lng": 79.8612 } },
  "SD": { "es": "Sudán", "en": "Sudan", "coordinates": { "lat": 15.5007, "lng": 32.5599 } },
  "SR": { "es": "Surinam", "en": "Suriname", "coordinates": { "lat": 5.8664, "lng": -55.1710 } },
  "SJ": { "es": "Islas Svalbard y Jan Mayen", "en": "Svalbard and Jan Mayen", "coordinates": { "lat": 78.2232, "lng": 15.6469 } },
  "SE": { "es": "Suecia", "en": "Sweden", "coordinates": { "lat": 59.3326, "lng": 18.0649 } },
  "CH": { "es": "Suiza", "en": "Switzerland", "coordinates": { "lat": 46.9481, "lng": 7.4474 } },
  "SY": { "es": "Siria", "en": "Syria", "coordinates": { "lat": 33.5138, "lng": 36.2765 } },
  "TW": { "es": "Taiwán", "en": "Taiwan", "coordinates": { "lat": 25.0324, "lng": 121.5645 } },
  "TJ": { "es": "Tayikistán", "en": "Tajikistan", "coordinates": { "lat": 38.5598, "lng": 68.7775 } },
  "TH": { "es": "Tailandia", "en": "Thailand", "coordinates": { "lat": 13.7563, "lng": 100.5018 } },
  "TZ": { "es": "Tanzania", "en": "Tanzania", "coordinates": { "lat": -6.7924, "lng": 39.2083 } },
  "TL": { "es": "Timor Oriental", "en": "East Timor", "coordinates": { "lat": -8.5567, "lng": 125.5749 } },
  "TG": { "es": "Togo", "en": "Togo", "coordinates": { "lat": 6.1369, "lng": 1.2123 } },
  "TK": { "es": "Tokelau", "en": "Tokelau", "coordinates": { "lat": -9.2003, "lng": -171.8575 } },
  "TO": { "es": "Tonga", "en": "Tonga", "coordinates": { "lat": -21.1340, "lng": -175.2011 } },
  "TT": { "es": "Trinidad y Tobago", "en": "Trinidad and Tobago", "coordinates": { "lat": 10.6918, "lng": -61.2225 } },
  "TN": { "es": "Túnez", "en": "Tunisia", "coordinates": { "lat": 36.8000, "lng": 10.1797 } },
  "TR": { "es": "Turquía", "en": "Turkey", "coordinates": { "lat": 39.9334, "lng": 32.8597 } },
  "TM": { "es": "Turkmenistán", "en": "Turkmenistan", "coordinates": { "lat": 39.1981, "lng": 59.4145 } },
  "TC": { "es": "Islas Turcas y Caicos", "en": "Turks and Caicos Islands", "coordinates": { "lat": 21.6947, "lng": -71.7979 } },
  "TV": { "es": "Tuvalu", "en": "Tuvalu", "coordinates": { "lat": -7.1095, "lng": 179.1940 } },
  "UG": { "es": "Uganda", "en": "Uganda", "coordinates": { "lat": 0.3136, "lng": 32.5818 } },
  "UA": { "es": "Ucrania", "en": "Ukraine", "coordinates": { "lat": 50.4501, "lng": 30.5427 } },
  "AE": { "es": "Emiratos Árabes Unidos", "en": "United Arab Emirates", "coordinates": { "lat": 25.276987, "lng": 51.520008 } },
  "GB": { "es": "Reino Unido", "en": "United Kingdom", "coordinates": { "lat": 51.5074, "lng": -0.1278 } },
  "US": { "es": "Estados Unidos", "en": "United States of America", "coordinates": { "lat": 38.9072, "lng": -77.0369 } },
  "UR": { "es": "Uruguay", "en": "Uruguay", "coordinates": { "lat": -34.9011, "lng": -56.1645 } },
  "UZ": { "es": "Uzbekistán", "en": "Uzbekistan", "coordinates": { "lat": 41.2995, "lng": 69.2401 } },
  "VU": { "es": "Vanuatu", "en": "Vanuatu", "coordinates": { "lat": -17.7333, "lng": 168.3219 } },
  "VE": { "es": "Venezuela", "en": "Venezuela", "coordinates": { "lat": 10.4925, "lng": -66.8792 } },
  "VN": { "es": "Vietnam", "en": "Vietnam", "coordinates": { "lat": 21.0285, "lng": 105.8542 } },
  "WF": { "es": "Islas Wallis y Futuna", "en": "Wallis and Futuna", "coordinates": { "lat": -13.2825, "lng": -176.2045 } },
  "EH": { "es": "Sáhara Occidental", "en": "Western Sahara", "coordinates": { "lat": 24.6349, "lng": -12.8921 } },
  "YE": { "es": "Yemen", "en": "Yemen", "coordinates": { "lat": 15.3694, "lng": 44.1910 } },
  "ZM": { "es": "Zambia", "en": "Zambia", "coordinates": { "lat": -15.3875, "lng": 28.3221 } },
  "ZW": { "es": "Zimbabue", "en": "Zimbabwe", "coordinates": { "lat": -17.8292, "lng": 31.0522 } }
}



//All country codes
const all_country_codes = Object.keys(all_countries);
//EU countries
const europe_countries = {
  "AT": { "es": "Austria", "en": "Austria" },
  "BE": { "es": "Bélgica", "en": "Belgium" },
  "BG": { "es": "Bulgaria", "en": "Bulgaria" },
  "HR": { "es": "Croacia", "en": "Croatia" },
  "CY": { "es": "Chipre", "en": "Cyprus" },
  "CZ": { "es": "República Checa", "en": "Czech Republic" },
  "DK": { "es": "Dinamarca", "en": "Denmark" },
  "EE": { "es": "Estonia", "en": "Estonia" },
  "FI": { "es": "Finlandia", "en": "Finland" },
  "FR": { "es": "Francia", "en": "France" },
  "DE": { "es": "Alemania", "en": "Germany" },
  "GR": { "es": "Grecia", "en": "Greece" },
  "HU": { "es": "Hungría", "en": "Hungary" },
  "IE": { "es": "Irlanda", "en": "Ireland" },
  "IT": { "es": "Italia", "en": "Italy" },
  "LV": { "es": "Letonia", "en": "Latvia" },
  "LT": { "es": "Lituania", "en": "Lithuania" },
  "LU": { "es": "Luxemburgo", "en": "Luxembourg" },
  "MT": { "es": "Malta", "en": "Malta" },
  "NL": { "es": "Países Bajos", "en": "Netherlands" },
  "PL": { "es": "Polonia", "en": "Poland" },
  "PT": { "es": "Portugal", "en": "Portugal" },
  "RO": { "es": "Rumanía", "en": "Romania" },
  "SK": { "es": "Eslovaquia", "en": "Slovakia" },
  "SI": { "es": "Eslovenia", "en": "Slovenia" },
  "ES": { "es": "España", "en": "Spain" },
  "SE": { "es": "Suecia", "en": "Sweden" },
  "IS": { "es": "Islandia", "en": "Iceland" },
  "AL": { "es": "Albania", "en": "Albania" },
  "AM": { "es": "Armenia", "en": "Armenia" },
  "AZ": { "es": "Azerbaiyán", "en": "Azerbaijan" },
  "BY": { "es": "Bielorrusia", "en": "Belarus" },
  "MD": { "es": "Moldavia", "en": "Moldova" },
  "MC": { "es": "Mónaco", "en": "Monaco" },
  "RS": { "es": "Serbia", "en": "Republic of Serbia" },
  "ME": { "es": "Montenegro", "en": "Montenegro" },
  "MK": { "es": "Macedonia", "en": "Macedonia" },
  "GE": { "es": "Georgia", "en": "Georgia" },
  "TR": { "es": "Turquía", "en": "Turkey" },
  "UA": { "es": "Ucrania", "en": "Ukraine" },
  "RU": { "es": "Rusia", "en": "Russia" },
  "GB": { "es": "Reino Unido", "en": "United Kingdom" },
  "NO": { "es": "Noruega", "en": "Norway" },
  "CH": { "es": "Suiza", "en": "Switzerland" }
};

//
const europe_codes = Object.keys(europe_countries);

//America countries
const america_countries = {
  "AQ": {"es": "Antártida","en": "Antarctica","coordinates": {"lat": -82.8628,"lng": 135.0000}},
  "GS": {"es": "Islas Georgias y Sandwich ","en": " Georgia and Sandwich Islands","coordinates": {"lat": -54.4296,"lng": -36.5870}},
  "AR": { "es": "Argentina", "en": "Argentina" },
  "BR": { "es": "Brasil", "en": "Brazil" },
  "CA": { "es": "Canadá", "en": "Canada" },
  "CL": { "es": "Chile", "en": "Chile" },
  "CO": { "es": "Colombia", "en": "Colombia" },
  "CR": { "es": "Costa Rica", "en": "Costa Rica" },
  "CU": { "es": "Cuba", "en": "Cuba" },
  "DO": { "es": "República Dominicana", "en": "Dominican Republic" },
  "EC": { "es": "Ecuador", "en": "Ecuador" },
  "SV": { "es": "El Salvador", "en": "El Salvador" },
  "GT": { "es": "Guatemala", "en": "Guatemala" },
  "HN": { "es": "Honduras", "en": "Honduras" },
  "MX": { "es": "México", "en": "Mexico" },
  "NI": { "es": "Nicaragua", "en": "Nicaragua" },
  "PA": { "es": "Panamá", "en": "Panama" },
  "PY": { "es": "Paraguay", "en": "Paraguay" },
  "PE": { "es": "Perú", "en": "Peru" },
  "PR": { "es": "Puerto Rico", "en": "Puerto Rico" },
  "UR": { "es": "Uruguay", "en": "Uruguay" },
  "VE": { "es": "Venezuela", "en": "Venezuela" },
  "US": { "es": "Estados Unidos", "en": "United States of America" },
  "BZ": { "es": "Belice", "en": "Belize" },
  "SR": { "es": "Surinam", "en": "Suriname" },
  "JM": { "es": "Jamaica", "en": "Jamaica" },
  "HT": { "es": "Haití", "en": "Haiti" },
  "BB": { "es": "Barbados", "en": "Barbados" },
  "LC": { "es": "Santa Lucía", "en": "Saint Lucia" },
  "KN": { "es": "San Cristóbal y Nieves", "en": "Saint Kitts and Nevis" },
  "VC": { "es": "San Vicente y las Granadinas", "en": "Saint Vincent and the Grenadines" },
  "TT": { "es": "Trinidad y Tobago", "en": "Trinidad and Tobago" },
  "GL": { "es": "Groenlandia", "en": "Greenland" },
  "FK": { "es": "Islas Malvinas", "en": "Falkland Islands" },
  "BO": { "es": "Bolivia", "en": "Bolivia" },
  "BL": { "es": "San Bartolomé", "en": "Saint Barthélemy" },
  "PF": { "es": "Polinesia Francesa", "en": "French Polynesia" },
  "PM": { "es": "San Pedro y Miquelón", "en": "Saint Pierre and Miquelon" },
  "AS": { "es": "Samoa Americana", "en": "American Samoa" },
  "AW": { "es": "Aruba", "en": "Aruba" },
  "AI": { "es": "Anguila", "en": "Anguilla" },
  "KY": { "es": "Islas Caimán", "en": "Cayman Islands" },
  "TC": { "es": "Islas Turcas y Caicos", "en": "Turks and Caicos Islands" },
  "FM": { "es": "Micronesia", "en": "Micronesia" },
  "GU": { "es": "Guam", "en": "Guam" },
  "VI": { "es": "Islas Vírgenes de los EE. UU.", "en": "U.S. Virgin Islands" },
  "BS": { "es": "Bahamas", "en": "Bahamas" },
  "BL": { "es": "San Bartolomé", "en": "Saint Barthelemy" },
  "GY": { "es": "Guyana", "en": "Guyana", "coordinates": { "lat": 4.8604, "lng": -58.9302 } },
  "DM": { "es": "Dominica", "en": "Dominica", "coordinates": { "lat": 15.4148, "lng": -61.3707 } },
  "AG": {"es": "Antigua y Barbuda","en": "Antigua and Barbuda","coordinates": {"lat": 17.0608,"lng": -61.7964}},
  "MS": { "es": "Montserrat", "en": "Montserrat", "coordinates": { "lat": 16.7425, "lng": -62.2181 } }
};
//
const america_codes = Object.keys(america_countries);
