//All countries
const all_countries = {
    "AF": {"es": "Afganistán", "en": "Afghanistan"},
    "AX": {"es": "Islas Åland", "en": "Åland Islands"},
    "AL": {"es": "Albania", "en": "Albania"},
    "DZ": {"es": "Argelia", "en": "Algeria"},
    "AS": {"es": "Samoa Americana", "en": "American Samoa"},
    "AD": {"es": "Andorra", "en": "Andorra"},
    "AO": {"es": "Angola", "en": "Angola"},
    "AI": {"es": "Anguila", "en": "Anguilla"},
    "AQ": {"es": "Antártida", "en": "Antarctica"},
    "AG": {"es": "Antigua y Barbuda", "en": "Antigua and Barbuda"},
    "AR": {"es": "Argentina", "en": "Argentina"},
    "AM": {"es": "Armenia", "en": "Armenia"},
    "AW": {"es": "Aruba", "en": "Aruba"},
    "AU": {"es": "Australia", "en": "Australia"},
    "AT": {"es": "Austria", "en": "Austria"},
    "AZ": {"es": "Azerbaiyán", "en": "Azerbaijan"},
    "BS": {"es": "Bahamas", "en": "Bahamas"},
    "BH": {"es": "Baréin", "en": "Bahrain"},
    "BD": {"es": "Bangladés", "en": "Bangladesh"},
    "BB": {"es": "Barbados", "en": "Barbados"},
    "BY": {"es": "Bielorrusia", "en": "Belarus"},
    "BE": {"es": "Bélgica", "en": "Belgium"},
    "BZ": {"es": "Belice", "en": "Belize"},
    "BJ": {"es": "Benín", "en": "Benin"},
    "BM": {"es": "Bermudas", "en": "Bermuda"},
    "BT": {"es": "Bután", "en": "Bhutan"},
    "BO": {"es": "Bolivia", "en": "Bolivia"},
    "BA": {"es": "Bosnia y Herzegovina", "en": "Bosnia and Herzegovina"},
    "BW": {"es": "Botsuana", "en": "Botswana"},
    "BV": {"es": "Isla Bouvet", "en": "Bouvet Island"},
    "BR": {"es": "Brasil", "en": "Brazil"},
    "IO": {"es": "Territorio Británico del Océano Índico", "en": "British Indian Ocean Territory"},
    "BN": {"es": "Brunéi", "en": "Brunei Darussalam"},
    "BG": {"es": "Bulgaria", "en": "Bulgaria"},
    "BF": {"es": "Burkina Faso", "en": "Burkina Faso"},
    "BI": {"es": "Burundi", "en": "Burundi"},
    "KH": {"es": "Camboya", "en": "Cambodia"},
    "CM": {"es": "Camerún", "en": "Cameroon"},
    "CA": {"es": "Canadá", "en": "Canada"},
    "CV": {"es": "Cabo Verde", "en": "Cape Verde"},
    "KY": {"es": "Islas Caimán", "en": "Cayman Islands"},
    "CF": {"es": "República Centroafricana", "en": "Central African Republic"},
    "TD": {"es": "Chad", "en": "Chad"},
    "CL": {"es": "Chile", "en": "Chile"},
    "CN": {"es": "China", "en": "China"},
    "CX": {"es": "Isla de Navidad", "en": "Christmas Island"},
    "CC": {"es": "Islas Cocos", "en": "Cocos (Keeling) Islands"},
    "CO": {"es": "Colombia", "en": "Colombia"},
    "KM": {"es": "Comoras", "en": "Comoros"},
    "CG": {"es": "Congo", "en": "Congo"},
    "CD": {"es": "República Democrática del Congo", "en": "Congo, The Democratic Republic of the"},
    "CK": {"es": "Islas Cook", "en": "Cook Islands"},
    "CR": {"es": "Costa Rica", "en": "Costa Rica"},
    "CI": {"es": "Costa de Marfil", "en": "Côte d'Ivoire"},
    "HR": {"es": "Croacia", "en": "Croatia"},
    "CU": {"es": "Cuba", "en": "Cuba"},
    "CY": {"es": "Chipre", "en": "Cyprus"},
    "CZ": {"es": "República Checa", "en": "Czech Republic"},
    "DK": {"es": "Dinamarca", "en": "Denmark"},
    "DJ": {"es": "Yibuti", "en": "Djibouti"},
    "DM": {"es": "Dominica", "en": "Dominica"},
    "DO": {"es": "República Dominicana", "en": "Dominican Republic"},
    "EC": {"es": "Ecuador", "en": "Ecuador"},
    "EG": {"es": "Egipto", "en": "Egypt"},
    "SV": {"es": "El Salvador", "en": "El Salvador"},
    "GQ": {"es": "Guinea Ecuatorial", "en": "Equatorial Guinea"},
    "ER": {"es": "Eritrea", "en": "Eritrea"},
    "EE": {"es": "Estonia", "en": "Estonia"},
    "ET": {"es": "Etiopía", "en": "Ethiopia"},
    "FK": {"es": "Islas Malvinas", "en": "Falkland Islands"},
    "FO": {"es": "Islas Feroe", "en": "Faroe Islands"},
    "FJ": {"es": "Fiyi", "en": "Fiji"},
    "FI": {"es": "Finlandia", "en": "Finland"},
    "FR": {"es": "Francia", "en": "France"},
    "GF": {"es": "Guayana Francesa", "en": "French Guiana"},
    "PF": {"es": "Polinesia Francesa", "en": "French Polynesia"},
    "TF": {"es": "Territorios Australes Franceses", "en": "French Southern Territories"},
    "GA": {"es": "Gabón", "en": "Gabon"},
    "GM": {"es": "Gambia", "en": "Gambia"},
    "GE": {"es": "Georgia", "en": "Georgia"},
    "DE": {"es": "Alemania", "en": "Germany"},
    "GH": {"es": "Ghana", "en": "Ghana"},
    "GI": {"es": "Gibraltar", "en": "Gibraltar"},
    "GR": {"es": "Grecia", "en": "Greece"},
    "GL": {"es": "Groenlandia", "en": "Greenland"},
    "GD": {"es": "Granada", "en": "Grenada"},
    "GP": {"es": "Guadalupe", "en": "Guadeloupe"},
    "GU": {"es": "Guam", "en": "Guam"},
    "GT": {"es": "Guatemala", "en": "Guatemala"},
    "GG": {"es": "Guernsey", "en": "Guernsey"},
    "GN": {"es": "Guinea", "en": "Guinea"},
    "GW": {"es": "Guinea-Bisáu", "en": "Guinea-Bissau"},
    "GY": {"es": "Guyana", "en": "Guyana"},
    "HT": {"es": "Haití", "en": "Haiti"},
    "HM": {"es": "Islas Heard y McDonald", "en": "Heard Island and McDonald Islands"},
    "VA": {"es": "Vaticano", "en": "Holy See (Vatican City State)"},
    "HN": {"es": "Honduras", "en": "Honduras"},
    "HK": {"es": "Hong Kong", "en": "Hong Kong"},
    "HU": {"es": "Hungría", "en": "Hungary"},
    "IS": {"es": "Islandia", "en": "Iceland"},
    "IN": {"es": "India", "en": "India"},
    "ID": {"es": "Indonesia", "en": "Indonesia"},
    "IR": {"es": "Irán", "en": "Iran, Islamic Republic of"},
    "IQ": {"es": "Irak", "en": "Iraq"},
    "IE": {"es": "Irlanda", "en": "Ireland"},
    "IL": {"es": "Israel", "en": "Israel"},
    "IT": {"es": "Italia", "en": "Italy"},
    "JM": {"es": "Jamaica", "en": "Jamaica"},
    "JP": {"es": "Japón", "en": "Japan"},
    "JO": {"es": "Jordania", "en": "Jordan"},
    "KZ": {"es": "Kazajistán", "en": "Kazakhstan"},
    "KE": {"es": "Kenia", "en": "Kenya"},
    "KI": {"es": "Kiribati", "en": "Kiribati"},
    "KW": {"es": "Kuwait", "en": "Kuwait"},
    "KG": {"es": "Kirguistán", "en": "Kyrgyzstan"},
    "LA": {"es": "Laos", "en": "Lao People's Democratic Republic"},
    "LV": {"es": "Letonia", "en": "Latvia"},
    "LB": {"es": "Líbano", "en": "Lebanon"},
    "LS": {"es": "Lesoto", "en": "Lesotho"},
    "LR": {"es": "Liberia", "en": "Liberia"},
    "LY": {"es": "Libia", "en": "Libya"},
    "LI": {"es": "Liechtenstein", "en": "Liechtenstein"},
    "LT": {"es": "Lituania", "en": "Lithuania"},
    "LU": {"es": "Luxemburgo", "en": "Luxembourg"},
    "MO": {"es": "Macao", "en": "Macao"},
    "MK": {"es": "Macedonia", "en": "Macedonia"},
    "MG": {"es": "Madagascar", "en": "Madagascar"},
    "MW": {"es": "Malawi", "en": "Malawi"},
    "MY": {"es": "Malasia", "en": "Malaysia"},
    "MV": {"es": "Maldivas", "en": "Maldives"},
    "ML": {"es": "Malí", "en": "Mali"},
    "MT": {"es": "Malta", "en": "Malta"},
    "MH": {"es": "Islas Marshall", "en": "Marshall Islands"},
    "MQ": {"es": "Martinica", "en": "Martinique"},
    "MR": {"es": "Mauritania", "en": "Mauritania"},
    "MU": {"es": "Mauricio", "en": "Mauritius"},
    "YT": {"es": "Mayotte", "en": "Mayotte"},
    "MX": {"es": "México", "en": "Mexico"},
    "FM": {"es": "Micronesia", "en": "Micronesia (Federated States of)"},
    "MD": {"es": "Moldavia", "en": "Moldova"},
    "MC": {"es": "Mónaco", "en": "Monaco"},
    "MN": {"es": "Mongolia", "en": "Mongolia"},
    "ME": {"es": "Montenegro", "en": "Montenegro"},
    "MA": {"es": "Marruecos", "en": "Morocco"},
    "MZ": {"es": "Mozambique", "en": "Mozambique"},
    "MM": {"es": "Birmania", "en": "Myanmar"},
    "NA": {"es": "Namibia", "en": "Namibia"},
    "NR": {"es": "Nauru", "en": "Nauru"},
    "NP": {"es": "Nepal", "en": "Nepal"},
    "NL": {"es": "Países Bajos", "en": "Netherlands"},
    "NC": {"es": "Nueva Caledonia", "en": "New Caledonia"},
    "NZ": {"es": "Nueva Zelanda", "en": "New Zealand"},
    "NI": {"es": "Nicaragua", "en": "Nicaragua"},
    "NE": {"es": "Níger", "en": "Niger"},
    "NG": {"es": "Nigeria", "en": "Nigeria"},
    "NU": {"es": "Niue", "en": "Niue"},
    "NF": {"es": "Isla Norfolk", "en": "Norfolk Island"},
    "KP": {"es": "Corea del Norte", "en": "North Korea"},
    "MP": {"es": "Islas Marianas del Norte", "en": "Northern Mariana Islands"},
    "NO": {"es": "Noruega", "en": "Norway"},
    "OM": {"es": "Omán", "en": "Oman"},
    "PK": {"es": "Pakistán", "en": "Pakistan"},
    "PW": {"es": "Palaos", "en": "Palau"},
    "PA": {"es": "Panamá", "en": "Panama"},
    "PG": {"es": "Papúa Nueva Guinea", "en": "Papua New Guinea"},
    "PY": {"es": "Paraguay", "en": "Paraguay"},
    "PE": {"es": "Perú", "en": "Peru"},
    "PH": {"es": "Filipinas", "en": "Philippines"},
    "PN": {"es": "Islas Pitcairn", "en": "Pitcairn Islands"},
    "PL": {"es": "Polonia", "en": "Poland"},
    "PT": {"es": "Portugal", "en": "Portugal"},
    "PR": {"es": "Puerto Rico", "en": "Puerto Rico"},
    "QA": {"es": "Catar", "en": "Qatar"},
    "RE": {"es": "Reunión", "en": "Réunion"},
    "RO": {"es": "Rumanía", "en": "Romania"},
    "RU": {"es": "Rusia", "en": "Russia"},
    "RW": {"es": "Ruanda", "en": "Rwanda"},
    "BL": {"es": "San Bartolomé", "en": "Saint Barthélemy"},
    "SH": {"es": "Santa Elena", "en": "Saint Helena, Ascension and Tristan da Cunha"},
    "KN": {"es": "San Cristóbal y Nieves", "en": "Saint Kitts and Nevis"},
    "LC": {"es": "Santa Lucía", "en": "Saint Lucia"},
    "MF": {"es": "San Martín", "en": "Saint Martin"},
    "PM": {"es": "San Pedro y Miquelón", "en": "Saint Pierre and Miquelon"},
    "VC": {"es": "San Vicente y las Granadinas", "en": "Saint Vincent and the Grenadines"},
    "WS": {"es": "Samoa", "en": "Samoa"},
    "SM": {"es": "San Marino", "en": "San Marino"},
    "ST": {"es": "Santo Tomé y Príncipe", "en": "Sao Tome and Principe"},
    "SA": {"es": "Arabia Saudita", "en": "Saudi Arabia"},
    "SN": {"es": "Senegal", "en": "Senegal"},
    "RS": {"es": "Serbia", "en": "Republic of Serbia"},
    "SC": {"es": "Seychelles", "en": "Seychelles"},
    "SL": {"es": "Sierra Leona", "en": "Sierra Leone"},
    "SG": {"es": "Singapur", "en": "Singapore"},
    "SX": {"es": "Sint Maarten", "en": "Sint Maarten"},
    "SK": {"es": "Eslovaquia", "en": "Slovakia"},
    "SI": {"es": "Eslovenia", "en": "Slovenia"},
    "SB": {"es": "Islas Salomón", "en": "Solomon Islands"},
    "SO": {"es": "Somalia", "en": "Somalia"},
    "ZA": {"es": "Sudáfrica", "en": "South Africa"},
    "GS": {"es": "Islas Georgias del Sur", "en": "South Georgia and the South Sandwich Islands"},
    "SS": {"es": "Sudán del Sur", "en": "South Sudan"},
    "ES": {"es": "España", "en": "Spain"},
    "LK": {"es": "Sri Lanka", "en": "Sri Lanka"},
    "SD": {"es": "Sudán", "en": "Sudan"},
    "SR": {"es": "Surinam", "en": "Suriname"},
    "SJ": {"es": "Svalbard y Jan Mayen", "en": "Svalbard and Jan Mayen"},
    "SZ": {"es": "Suazilandia", "en": "Swaziland"},
    "SE": {"es": "Suecia", "en": "Sweden"},
    "CH": {"es": "Suiza", "en": "Switzerland"},
    "SY": {"es": "Siria", "en": "Syrian Arab Republic"},
    "TW": {"es": "Taiwán", "en": "Taiwan"},
    "TJ": {"es": "Tayikistán", "en": "Tajikistan"},
    "TZ": {"es": "Tanzania", "en": "Tanzania"},
    "TH": {"es": "Tailandia", "en": "Thailand"},
    "TL": {"es": "Timor Oriental", "en": "Timor-Leste"},
    "TG": {"es": "Togo", "en": "Togo"},
    "TK": {"es": "Tokelau", "en": "Tokelau"},
    "TO": {"es": "Tonga", "en": "Tonga"},
    "TT": {"es": "Trinidad y Tobago", "en": "Trinidad and Tobago"},
    "TN": {"es": "Túnez", "en": "Tunisia"},
    "TR": {"es": "Turquía", "en": "Turkey"},
    "TM": {"es": "Turkmenistán", "en": "Turkmenistan"},
    "TC": {"es": "Islas Turcas y Caicos", "en": "Turks and Caicos Islands"},
    "TV": {"es": "Tuvalu", "en": "Tuvalu"},
    "UG": {"es": "Uganda", "en": "Uganda"},
    "UA": {"es": "Ucrania", "en": "Ukraine"},
    "AE": {"es": "Emiratos Árabes Unidos", "en": "United Arab Emirates"},
    "GB": {"es": "Reino Unido", "en": "United Kingdom"},
    "US": {"es": "Estados Unidos", "en": "United States of America"},
    "UY": {"es": "Uruguay", "en": "Uruguay"},
    "UZ": {"es": "Uzbekistán", "en": "Uzbekistan"},
    "VU": {"es": "Vanuatu", "en": "Vanuatu"},
    "VE": {"es": "Venezuela", "en": "Venezuela"},
    "VN": {"es": "Vietnam", "en": "Vietnam"},
    "WF": {"es": "Wallis y Futuna", "en": "Wallis and Futuna"},
    "EH": {"es": "Sáhara Occidental", "en": "Western Sahara"},
    "YE": {"es": "Yemen", "en": "Yemen"},
    "ZM": {"es": "Zambia", "en": "Zambia"},
    "ZW": {"es": "Zimbabue", "en": "Zimbabwe"}
  };
  //All country codes
  const all_country_codes = Object.keys(all_countries);
  //EU countries
  const europe_countries = {
    "AT": {"es": "Austria", "en": "Austria"},
    "BE": {"es": "Bélgica", "en": "Belgium"},
    "BG": {"es": "Bulgaria", "en": "Bulgaria"},
    "HR": {"es": "Croacia", "en": "Croatia"},
    "CY": {"es": "Chipre", "en": "Cyprus"},
    "CZ": {"es": "República Checa", "en": "Czech Republic"},
    "DK": {"es": "Dinamarca", "en": "Denmark"},
    "EE": {"es": "Estonia", "en": "Estonia"},
    "FI": {"es": "Finlandia", "en": "Finland"},
    "FR": {"es": "Francia", "en": "France"},
    "DE": {"es": "Alemania", "en": "Germany"},
    "GR": {"es": "Grecia", "en": "Greece"},
    "HU": {"es": "Hungría", "en": "Hungary"},
    "IE": {"es": "Irlanda", "en": "Ireland"},
    "IT": {"es": "Italia", "en": "Italy"},
    "LV": {"es": "Letonia", "en": "Latvia"},
    "LT": {"es": "Lituania", "en": "Lithuania"},
    "LU": {"es": "Luxemburgo", "en": "Luxembourg"},
    "MT": {"es": "Malta", "en": "Malta"},
    "NL": {"es": "Países Bajos", "en": "Netherlands"},
    "PL": {"es": "Polonia", "en": "Poland"},
    "PT": {"es": "Portugal", "en": "Portugal"},
    "RO": {"es": "Rumanía", "en": "Romania"},
    "SK": {"es": "Eslovaquia", "en": "Slovakia"},
    "SI": {"es": "Eslovenia", "en": "Slovenia"},
    "ES": {"es": "España", "en": "Spain"},
    "SE": {"es": "Suecia", "en": "Sweden"},
    "IS": {"es": "Islandia", "en": "Iceland"},
    "AL": {"es": "Albania", "en": "Albania"},
    "AM": {"es": "Armenia", "en": "Armenia"},
    "AZ": {"es": "Azerbaiyán", "en": "Azerbaijan"},
    "BY": {"es": "Bielorrusia", "en": "Belarus"},
    "MD": {"es": "Moldavia", "en": "Moldova"},
    "MC": {"es": "Mónaco", "en": "Monaco"},
    "RS": {"es": "Serbia", "en": "Republic of Serbia"},
    "ME": {"es": "Montenegro", "en": "Montenegro"},
    "MK": {"es": "Macedonia", "en": "Macedonia"},
    "GE": {"es": "Georgia", "en": "Georgia"},
    "TR": {"es": "Turquía", "en": "Turkey"},
    "UA": {"es": "Ucrania", "en": "Ukraine"},
    "RU": {"es": "Rusia", "en": "Russia"},
    "GB": {"es": "Reino Unido", "en": "United Kingdom"},
    "NO": {"es": "Noruega", "en": "Norway"}
  };
  
  //
  const europe_codes = Object.keys(europe_countries);
  
  //America countries
  const america_countries = {
    "AR": {"es": "Argentina", "en": "Argentina"},
    "BR": {"es": "Brasil", "en": "Brazil"},
    "CA": {"es": "Canadá", "en": "Canada"},
    "CL": {"es": "Chile", "en": "Chile"},
    "CO": {"es": "Colombia", "en": "Colombia"},
    "CR": {"es": "Costa Rica", "en": "Costa Rica"},
    "CU": {"es": "Cuba", "en": "Cuba"},
    "DO": {"es": "República Dominicana", "en": "Dominican Republic"},
    "EC": {"es": "Ecuador", "en": "Ecuador"},
    "SV": {"es": "El Salvador", "en": "El Salvador"},
    "GT": {"es": "Guatemala", "en": "Guatemala"},
    "HN": {"es": "Honduras", "en": "Honduras"},
    "MX": {"es": "México", "en": "Mexico"},
    "NI": {"es": "Nicaragua", "en": "Nicaragua"},
    "PA": {"es": "Panamá", "en": "Panama"},
    "PY": {"es": "Paraguay", "en": "Paraguay"},
    "PE": {"es": "Perú", "en": "Peru"},
    "PR": {"es": "Puerto Rico", "en": "Puerto Rico"},
    "UR": {"es": "Uruguay", "en": "Uruguay"},
    "VE": {"es": "Venezuela", "en": "Venezuela"},
    "US": {"es": "Estados Unidos", "en": "United States of America"},
    "BZ": {"es": "Belice", "en": "Belize"},
    "GY": {"es": "Guyana", "en": "Guyana"},
    "SR": {"es": "Surinam", "en": "Suriname"},
    "JM": {"es": "Jamaica", "en": "Jamaica"},
    "HT": {"es": "Haití", "en": "Haiti"},
    "BB": {"es": "Barbados", "en": "Barbados"},
    "LC": {"es": "Santa Lucía", "en": "Saint Lucia"},
    "KN": {"es": "San Cristóbal y Nieves", "en": "Saint Kitts and Nevis"},
    "VC": {"es": "San Vicente y las Granadinas", "en": "Saint Vincent and the Grenadines"},
    "TT": {"es": "Trinidad y Tobago", "en": "Trinidad and Tobago"},
    "GL": {"es": "Groenlandia", "en": "Greenland"},
    "FK": {"es": "Islas Malvinas", "en": "Falkland Islands"},
    "MQ": {"es": "Martinica", "en": "Martinique"},
    "GP": {"es": "Guadalupe", "en": "Guadeloupe"},
    "BO": {"es": "Bolivia", "en": "Bolivia"},
    "BL": {"es": "San Bartolomé", "en": "Saint Barthélemy"},
    "GF": {"es": "Guayana Francesa", "en": "French Guiana"},
    "PF": {"es": "Polinesia Francesa", "en": "French Polynesia"},
    "PM": {"es": "San Pedro y Miquelón", "en": "Saint Pierre and Miquelon"},
    "AS": {"es": "Samoa Americana", "en": "American Samoa"},
    "AW": {"es": "Aruba", "en": "Aruba"},
    "AI": {"es": "Anguila", "en": "Anguilla"},
    "KY": {"es": "Islas Caimán", "en": "Cayman Islands"},
    "TC": {"es": "Islas Turcas y Caicos", "en": "Turks and Caicos Islands"},
    "FM": {"es": "Micronesia", "en": "Micronesia"},
    "GU": {"es": "Guam", "en": "Guam"},
    "VI": {"es": "Islas Vírgenes de los EE. UU.", "en": "U.S. Virgin Islands"},
    "BS": {"es": "Bahamas", "en": "Bahamas"},
    "BL": {"es": "San Bartolomé", "en": "Saint Barthelemy"},
  };
  //
  const america_codes = Object.keys(america_countries);
